# Generated by Django 6.0.5 on 2026-05-06 18:47

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Tashkilot nomi')),
                ('logo', models.FileField(blank=True, null=True, upload_to='org/logos/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_uz_phone])),
                ('status', models.CharField(choices=[('active', 'Aktiv holatda'), ('inactive', 'Aktiv emas'), ('expires', "To'lov muddati yaqin"), ('expired', "To'lov muddati tugagan")], default='active', max_length=20)),
                ('work_start_time', models.TimeField(blank=True, null=True, verbose_name='Ish boshlanishi')),
                ('work_end_time', models.TimeField(blank=True, null=True, verbose_name='Ish tugashi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tarif nomi (Start, Basic...)')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text="Cheksiz bo'lsa bo'sh qoldiring", null=True, verbose_name="Maksimal o'quvchilar soni")),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Oylik to'lov narxi")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Filial nomi')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_uz_phone])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Obuna boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Obuna tugash sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'langan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organizations')),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='organizations.tariffplan', verbose_name='Tanlangan tarif')),
            ],
        ),
    ]
