# Generated by Django 4.2.7 on 2026-05-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageSubmission',
        ),
    ]
