# Generated by Django 4.2.7 on 2026-05-09 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizations_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizations",
            name="password",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, message="Parol kamida 6 ta belgidan iborat bo‘lishi kerak"
                    )
                ],
            ),
        ),
    ]
