# Generated by Django 6.0.5 on 2026-05-06 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('student', 'Student'), ('payment', 'Payment'), ('group', 'Group'), ('user', 'User'), ('employee', 'Employee'), ('other', 'Other')], max_length=30)),
                ('entity_id', models.UUIDField(help_text="O'zgartirilgan entity (obyekt) UUID si")),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi")], max_length=20)),
                ('old_data', models.JSONField(blank=True, help_text="O'zgarishdan oldingi holat", null=True)),
                ('new_data', models.JSONField(blank=True, help_text="O'zgarishdan keyingi holat", null=True)),
                ('performed_by_role', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Jurnali',
                'verbose_name_plural': 'Audit Jurnallari',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_01c53f_idx')],
            },
        ),
    ]
